### ISSUE TITLE
ควาบคืบหน้าของงาน

### ISSUE THREAD

**Issue by TonNattapon** [Suwannapop/cpe103-test-group-4#10]

**Comment by TonNattapon** [comment]
5 กันยายน 2565
- ได้รูปแบบเกมที่จะทำแล้ว
- แบ่งงาน map , sound แล้ว
- ได้รายละเอียดระบบในเกมที่จะทำแล้ว

**Comment by TonNattapon** [comment]
6 กันยายน 2565
- map design ได้คร่าวๆแล้ว
- sound design ได้คร่าวๆแล้ว
- scope เกมคร่าวๆแล้ว
- engine list คร่าวๆแล้ว

**Comment by TonNattapon** [comment]
12 กันยายน   2565

- map lobby เสร็จแล้ว
- map ลานควายยิ้มเสร็จแล้ว
- ระบบ generate mon รอหาบัค

**Comment by fluk3G123** [comment]
Bug 1.ย้ายที่ monsters โดยการคลิกเมาส์ได้

**Comment by TonNattapon** [comment]
https://scratch.mit.edu/projects/731061346

**Comment by TonNattapon** [comment]
16 กันยายน 2565

- รวมระบบเคลื่อนไหวตัวละครกับศัตรูแล้ว
- อัพเดตแมพไปได้ 2 แมพแล้ว
- เหลือเพิ่มลูกเล่นให้มากขึ้นและเนื้อเรื่องของเกม
ยังมีบัคอยู่เล็กน้อย

**Comment by Suwannapop** [comment]
18 กันยา 
-เพิ่มระบบ covid ลอยไปมาไหม

**Comment by Suwannapop** [comment]
https://scratch.mit.edu/projects/733364077

**Comment by fluk3G123** [comment]
Code ล่าสุด 20/09/65 3:32 น.
https://scratch.mit.edu/projects/734081045
