### ISSUE TITLE
Pop-up text box

### ISSUE THREAD

**Issue by TonNattapon** [Suwannapop/cpe103-test-group-4#15]

**Comment by TonNattapon** [comment]
https://scratch.mit.edu/projects/729040171

**Comment by TonNattapon** [comment]
code เสร็จแล้ว เหลือออกแบบ text box

**Comment by Suwannapop** [comment]
ลองเขียนประโยคยาวๆ เเล้ว มันไม่ขึ้นบรรทัดใหม่
อะเพื่อน bug

**Comment by TonNattapon** [comment]
แก้แล้วเรียบร้อย
