### ISSUE TITLE
Generate Monsters Engine

### ISSUE THREAD

**Issue by TonNattapon** [Suwannapop/cpe103-test-group-4#18]

**Comment by fluk3G123** [comment]
gererate monsters คร่าวๆ
![image](https://user-images.githubusercontent.com/89276072/189146077-d6b6b815-ff18-4715-be39-65e87ab495f0.png)
![image](https://user-images.githubusercontent.com/89276072/189146172-54786b55-945a-4b2a-b3c3-45a9e67935d6.png)
![image](https://user-images.githubusercontent.com/89276072/189146212-8e8908c3-63cb-4166-ac42-12843907fe43.png)

**Comment by fluk3G123** [comment]
https://scratch.mit.edu/projects/729550053

**Comment by Suwannapop** [comment]
https://scratch.mit.edu/projects/731490357/
ได้เเล้วเเต่ monster ยังเดินเเบบ ลอยๆ
