### ISSUE TITLE
Statusbar Engine

### ISSUE THREAD

**Issue by TonNattapon** [Suwannapop/cpe103-test-group-4#19]

**Comment by TonNattapon** [comment]
- Health Bar
- Heal buff bar

**Comment by Suwannapop** [comment]
ลองเขียนประโยคยาวๆ เเล้ว มันไม่ขึ้นบรรทัดใหม่
อะเพื่อน bug

**Comment by Suwannapop** [comment]
https://scratch.mit.edu/projects/731969112/
