### ISSUE TITLE
Map 3 ลานควายยิ้ม

### ISSUE THREAD

**Issue by PantawatB** [Suwannapop/cpe103-test-group-4#22]

**Comment by PantawatB** [comment]
![6F05CACA-7187-4DE2-829D-B3B17CF550F4](https://user-images.githubusercontent.com/110970262/189350753-47dd8fe9-4af6-488d-b0c9-17de6aa2aec6.jpeg)

**Comment by fluk3G123** [comment]
สวยย แบบกูว่าดูออกเลยว่าเป็นลานควายยิ้ม

**Comment by Suwannapop** [comment]
เอาเรื่องอยู่นะครับเนี่ย

**Comment by PantawatB** [comment]
++Map Update++_1
![Screenshot 2022-09-11 153144](https://user-images.githubusercontent.com/110970262/189518702-a89c8e8f-c718-4a53-96e4-331988be659e.png)

**Comment by PantawatB** [comment]
Map 3!!!!!!!!!
![Screenshot 2022-09-11 172250](https://user-images.githubusercontent.com/110970262/189522506-b24d4620-7ef9-4e37-a1ed-22435e1539d0.png)

**Comment by PantawatB** [comment]
++Map for Scratch++
   -Spike
![Map 3 Spike](https://user-images.githubusercontent.com/110970262/189542916-7fbf2a60-3faf-4a19-87cb-9969c9c03cd3.png)
   -Background
![Map 3 Background](https://user-images.githubusercontent.com/110970262/189542931-84ec3f56-f0f7-4de6-b8e3-75e292240613.png)
