### ISSUE TITLE
Map 4 ลานจอดรถม่วง

### ISSUE THREAD

**Issue by PantawatB** [Suwannapop/cpe103-test-group-4#23]

**Comment by TonNattapon** [comment]
เปลี่ยนเป็น Map ลานจอดรถม่วง @Suwannapop แก้ชื่อ issue ด้วย

**Comment by PantawatB** [comment]
Update_1
![Screenshot 2022-09-15 011023](https://user-images.githubusercontent.com/110970262/190230112-d99e300c-67e1-4e60-aa70-00af8a529031.png)

**Comment by PantawatB** [comment]
Map Update 2
![Screenshot 2022-09-15 025854](https://user-images.githubusercontent.com/110970262/190250190-fb4e1038-16ff-443d-bf99-e95bf7bad331.png)

**Comment by PantawatB** [comment]
Map Update 3
![Screenshot 2022-09-16 031440](https://user-images.githubusercontent.com/110970262/190499709-cad2df4a-1de6-4b62-8675-9f597064669a.png)

**Comment by PantawatB** [comment]
Map done
![Screenshot 2022-09-16 042439](https://user-images.githubusercontent.com/110970262/190511147-5bc24ef3-970f-436f-bf21-edc05703773f.png)

**Comment by PantawatB** [comment]
Map for Scratch
![Map4 เดินติด](https://user-images.githubusercontent.com/110970262/190522932-9c073fc1-f99c-4e93-9e17-6f2ceddaf0e1.png)
![Map4 ทะลุผ่าน](https://user-images.githubusercontent.com/110970262/190522125-834d02d5-5675-413f-8a5c-f2ac654adb0f.png)
![Map4 ถนน](https://user-images.githubusercontent.com/110970262/190522138-b118490e-c119-4a63-adeb-2dfc4b84c140.png)
