### ISSUE TITLE
ideas เพิ่มลูกเล่น ให้เข้ากับ covid 19

### ISSUE THREAD

**Issue by TonNattapon** [Suwannapop/cpe103-test-group-4#28]

**Comment by TonNattapon** [comment]
- เพิ่มเวลานับถอยหลังไปเรื่อยๆ โดยต้องเคลียร์เกมก่อนเวลาจะหมดหลอด ทำให้เกม challenge ขึ้น

**Comment by TonNattapon** [comment]
comment จากอาจารย์ครั้งที่แล้วคือ

**Comment by Suwannapop** [comment]
เพิ่มีระบบ เวลาในการ ใส่ mask

**Comment by TonNattapon** [comment]
คอมเม้นจากอาจารย์ครั้งที่แล้ว
- เกมตรงตัวไปควรมีลูกเล่นเพิ่มเติม

**Comment by Suwannapop** [comment]
เพิ่ม covid ลอยไปลอยมาใน map ลดเลือด ผู้เล่นอยู่ตลอดเวลา

**Comment by Suwannapop** [comment]
![image](https://user-images.githubusercontent.com/110958686/190694568-a0177cb8-9c50-4339-9e47-70fb0b3c8f99.png)
