### ISSUE TITLE
Test game 

### ISSUE THREAD

**Issue by Suwannapop** [Suwannapop/cpe103-test-group-4#33]

**Comment by PantawatB** [comment]
Zombie เกิดในเซฟโซน
![image](https://user-images.githubusercontent.com/110970262/191333390-e5a34dc8-b362-462c-8f0e-e55e2a5152ed.png)

**Comment by Suwannapop** [comment]
รับทราบ เดี่ยวเเก้

**Comment by PantawatB** [comment]
เคลียร์แมพแรกแล้วประตูมีสองอัน
![image](https://user-images.githubusercontent.com/110970262/191334037-7a25de3c-49d3-4e18-89d2-ec1b534c0410.png)

**Comment by PantawatB** [comment]
บอสหาย
![image](https://user-images.githubusercontent.com/110970262/191334623-e9c677ca-d90b-4e17-a118-a9639bf9b97c.png)

**Comment by PantawatB** [comment]
ประตูเกิดผิดที่
![image](https://user-images.githubusercontent.com/110970262/191336030-9f7343ca-c336-41fe-be27-80080d82fc68.png)

**Comment by PantawatB** [comment]
เข้าประตูแล้วติดต้นไม้
![image](https://user-images.githubusercontent.com/110970262/191338687-28f35143-7b64-4c22-bbf0-fb30147449cd.png)

**Comment by PantawatB** [comment]
Zombie 2 ไม่ตาย
![image](https://user-images.githubusercontent.com/110970262/191338936-19bab816-637f-479b-b8e6-3a1425ef55a9.png)

**Comment by PantawatB** [comment]
เข้าวาปไม่ได้
![image](https://user-images.githubusercontent.com/110970262/191345646-e94e3261-c1c4-477b-9092-a983ede66513.png)

**Comment by Suwannapop** [comment]
All bug has fixed
