### ISSUE TITLE
นัดประชุมกลุ่มเลือกรูปแบบเกมที่จะทำ

### ISSUE THREAD

**Issue by TonNattapon** [Suwannapop/cpe103-test-group-4#4]

**Comment by Suwannapop** [comment]
1) เอาเป็นเกมส์ยิงที่มุมมองเป็นเเบบ bird eye view มุมมองเเบบด้านบนเเล้ว ตีมเกมส์เป็น covid 19 เป็นตัวร้ายเป็นคนที่ติดโควิดเเต่ ไม่ยอมใส่เเมส เเล้วเราเป็นคนที่ยังไม่ติดเเล้วยิงเเมสไปหาตัวร้าย ยิงไปจนกว่าเราจะตาย

**Comment by TonNattapon** [comment]
game design คร่าวๆ
<img width="1069" alt="Screen Shot 2565-08-17 at 15 33 53" src="https://user-images.githubusercontent.com/38356005/185073290-5e60e15a-9fb9-440a-b385-8630c8137ab2.png">

**Comment by TonNattapon** [comment]
assets ที่น่าจะใช้ทำ map ได้
https://craftpix.net/freebies/free-tropical-medieval-city-2d-tileset/

**Comment by TonNattapon** [comment]
www.meistertask.com

**Comment by TonNattapon** [comment]
task management tools
https://www.meistertask.com/app/project/fxrZvibh/scratch-game-project

**Comment by Suwannapop** [comment]
เอามุมมองเเบบนี้ไหมครับ 
https://www.youtube.com/watch?v=1EdlLjGhhEQ
มีการเก็บ ของเก็บยา เก็บกระสุน

**Comment by TonNattapon** [comment]
# SCRATCH GAME PROJECT

# Game name : Soul Clash → Scratch + Soul Knight

## Concept :

- Roguelike game ver.scratch

## **Game Goals :**

- ผ่านด่าน wave แต่ละ wave โดยต้องใช้เวลาเล่นประมาณ 5 นาทีโดยจะมีศัตรูโผล่ออกมาให้ยิงเรื่อย ๆ แต่ละ wave

## Game Plot

- เมื่อโลกได้เกิดการระบาดของเชื้อไวรัสโคโรน่า 19 และได้แพร่เชื่อไปทั่วทุกสารทิศทำให้มีประชากรโลกติดเชื้อเป็นจำนวนมากและได้ส่งผลกระทบถึงนักศึกษามหาวิทยาลัยเชียงใหม่ของเราด้วย จากเหตุการณ์ที่เกิดขึ้นจึงต้องมีผู้ที่จะมาช่วยเหลือนักศึกษาจากสถานการณ์นี้ 
     ซึ่งในตัวเกมส์ผู้เล่นจะได้รับบทบาทให้เป็นคนที่ยังไม่ได้รับเชื้อ ผู้เล่นต้องทำการเอาชีวิตรอดจากคนที่ติดเชื้อโควิด โดยต้องทำการใช้อาวุธในการต่อสู้และใช้ความคล่องแคล่วในการหลบหลีกเชื้อไวรัสที่จะแพร่มาจากผู้คนที่ติดเชื้อ และจะมีบอสใหญ่ในแต่ละด่านให้โค่นล้มเพื่อที่จะสามารถผ่านด่านไปช่วยเหลือกลุ่มนักศึกษาที่ถูกบอสโควิดลักพาตัวไปที่ลับที่หนึ่งในมช. ซึ่งเป็นสิ่งที่ผู้เล่นต้องผ่านด่านแต่ละด่านเพื่อไปค้นหายังจุดต่าง ๆ ที่คาดว่ากลุ่มนักศึกษาน่าจะถูกลักพาตัวไป 

## ความคืบหน้าของงาน :

- งานที่ทำไปแล้ว
    - เลือกแนวเกมที่จะทำ
    - คิดระบบคร่าวๆที่จะทำในเกม
- งานที่กำลังดำเนินการ
    - Map design
    - Sound effects design
    - coding

## How to play?

- ใช้การเคลื่อนไหวโดยการใช้ ปุ่ม W,A,S,D หรือ ลูกศร ในการเดิน
- คลิกซ้ายเพื่อใช้อาวุธ
- ตัวละครจะหันหน้าตามทิศทางเม้าส์ที่ชี้

## Features

- Movement Engine
- Scrolling RPG Engine
    - Pop-up text box
- Status Bar Engine
    - Health Bar
    - Buff effect Bar
        - Main character
        - Monsters
- Generate Monsters Engine
- Damage Engine

## จุดเด่น

- ทำให้เข้าสถานการณ์โควิดในปัจจุบันโดยการ มีการใช้ assets ต่างๆเป็นสิ่งที่เกี่ยวกับโควิด
- แมพเป็นสถานที่ landmark ของมหาวิทยาลัยเชียงใหม่
- มีแมพให้เล่นหลากหลาย
- ตัวละครเลือดมีเลือดเท่าเดิม แต่ศัตรูจะเก่งขึ้นเรื่อยๆ เหมาะสำหรับคนชอบเล่นเกมที่ท้าทาย
