### ISSUE TITLE
Map design

### ISSUE THREAD

**Issue by TonNattapon** [Suwannapop/cpe103-test-group-4#5]

**Comment by TonNattapon** [comment]
scratch map scale
![image](https://user-images.githubusercontent.com/38356005/188484346-a63d2bb7-f38c-4780-83e3-b2df3dbb468d.png)

**Comment by TonNattapon** [comment]
https://youtu.be/rLdA4Amea7Y

**Comment by TonNattapon** [comment]
ตอนทำแมพ แยก Layer กำแพงออกต่างหากจาก Layer ของแมพด้วย

**Comment by TonNattapon** [comment]
อันนี้ดีมาก มำแมพแบบไม่ต้องใช้ Ps ทำเป็น Pixel 
https://youtu.be/KkiEvojtKYc

**Comment by Suwannapop** [comment]
https://www.youtube.com/watch?v=1vB3XJ8OgAU การทำมุมกล้อง

**Comment by PantawatB** [comment]
ไอเดียแรกสถานที่บริเวณ มช

**Comment by Suwannapop** [comment]
![image](https://user-images.githubusercontent.com/110958686/188689466-e687825a-284b-4b13-966c-98209ac81977.png)![image](https://user-images.githubusercontent.com/110958686/188689487-3ad0ccbf-fd9d-4590-bd23-bdda1cb1ac5d.png)![image](https://user-images.githubusercontent.com/110958686/188689508-423cf3d6-29dc-4f9c-851a-775b236c1239.png)![image](https://user-images.githubusercontent.com/110958686/188689527-529c7734-37d3-43c4-8b59-c77df71149ff.png)

Mapเเบบร่าง

**Comment by Suwannapop** [comment]
เดี่ยวจะ map เป็น pixel

**Comment by Suwannapop** [comment]
![safezone](https://user-images.githubusercontent.com/110958686/188877566-855caec9-a209-421d-a6fd-5c9773abc861.png)
safe zone room

**Comment by Suwannapop** [comment]
![Uploading 188889156...]
ยังไม่ได้ทำmap ปอดหมด เเต่เอามาใช้ได้เเล้ว

**Comment by Suwannapop** [comment]
![safezone-type-wall-](https://user-images.githubusercontent.com/110958686/188890613-04a3af3b-69e0-42f2-ae8b-f88c231eb2d3.png)
![safezone-typre-flore](https://user-images.githubusercontent.com/110958686/188890615-94c11ee0-fd84-42e2-8de7-a61252f302fd.png)

**Comment by Suwannapop** [comment]
map design is done!!!!
