### ISSUE TITLE
Character design

### ISSUE THREAD

**Issue by TonNattapon** [Suwannapop/cpe103-test-group-4#6]

**Comment by TonNattapon** [comment]
ตัวหลัก (สกิลโจมตีเป็น mask พุ่งออกไป)
https://craftpix.net/freebies/free-fallen-angel-chibi-2d-game-sprites/

**Comment by Suwannapop** [comment]
ได้เลยๆ ทำเอานั้นเลยพี่

**Comment by Suwannapop** [comment]
![image](https://user-images.githubusercontent.com/110958686/188689735-524a0dd5-f1cb-43ed-8175-7e10fa38c3f2.png)![image](https://user-images.githubusercontent.com/110958686/188689751-62926b15-ffc3-4056-9fc4-e106c680c2b9.png)

**Comment by TonNattapon** [comment]
เหลือเอามาออกแบบเป็น digital art
